//import logo from './images/download.jpg';

export default {
    products:[{
       // image:{logo},
        _id:'1',
        name:'Balisong',
        price:350,
        rating:3.8,
        review:20,
        description:'Perfect to murder',
        status:'Available',
        countINstock: 8,
    },
    {
       // image:'./images/download.jpg',
        _id:'2',
        name:'Swiss-Knife',
        price:500,
        rating:4,
        review:35,
        description:'Not made in swiss',
        status:'Available',
        countINstock: 6,
    },
    {
       // image:{logo},
        _id:'3',
        name:'kitchen-knife',
        price:200,
        rating:2.5,
        review:15,
        description:'sabji kate jaise butter',
        status:'Available',
        countINstock: 0,
    },
    {
      //  image:{logo},
        _id:'4',
        name:'Pocket-Knife',
        price:250,
        rating:4.5,
        review:22,
        description:'When in pocket keep closed',
        status:'Available',
        countINstock: 9,
    },
    {
      //  image:{logo},
        _id:'5',
        name:'Carve-Knife',
        price:170,
        rating:3.6,
        review:29,
        description:'Perfect to hide body',
        status:'Available',
        countINstock: 4,
    }
]
}